export const CHANGE_AUTH_FIELD = "CHANGE_AUTH_FIELD";
export const CHANGE_AUTH_FIELD_ERROR = "CHANGE_AUTH_FIELD_ERROR"; 
export const SEND_AUTH = "SEND_AUTH";
export const CLEAR_FIELDS = "CLEAR_FIELDS";
