export const CHANGE_REGISTRATION_FIELD = "CHANGE_REGISTRATION_FIELD";
export const CHANGE_REGISTRATION_FIELD_ERROR = "CHANGE_REGISTRATION_FIELD_ERROR";
export const SEND_REGISTRATION = "SEND_REGISTRATION";
export const CLEAR_INPUTS_VALUES = 'CLEAR_INPUTS_VALUES';
